#!/bin/bash
#curl -H "Authorization: token 323f10206117840822c9a316245833dd1768996a" https://api.github.com

# Dados do repositório
user="jessielyoliveira"
repo="projeto-gcm"

msgCommit=$(cat $1)
pattern=#[0-9]

if [[ ! $msgCommit =~ $pattern ]];
then
    echo "O commit deve estar no padrão: #{numero_da_issue} - {mensagem}"
    exit 1
fi

# Separa só a primeira ocorrência de dígitos para identificar o número da issue
numberIssue="$(echo $msgCommit | grep -o -E '[0-9]+')"
numberIssue="$(echo $numberIssue | cut -f1 -d ' ')"

# Pega os dados da issue na api do github
url="https://api.github.com/repos/$user/$repo/issues/$numberIssue"
jsonIssue=$(curl -s $url)

# Verifica se possui issue com o número informado
message="$(echo $jsonIssue | jq -r '.message')"
if [ "$message" == "Not Found" ];
then
    echo "Não existe issue com o número informado."
    exit 1
fi

# Verifica se a issue está aberta e atribuída a algum usuário
state="$(echo $jsonIssue | jq -r '.state')"
devs="$(echo $jsonIssue | jq -r '.assignees')"

if [[ "$devs" == "[]" ]] || [[ "$state" != "open" ]];
then
    echo "Issue não está habilitada para desenvolvimento. É necessário estar aberta e atribuída à um usuário."
    exit 1
fi

