#!/bin/bash

# Dados do repositório
user="jessielyoliveira"
repo="projeto-gcm"

msgCommit="$(git show --format='%B' -s $SHA1)"

# Separa só a primeira ocorrência de dígitos para identificar o número da issue
numberIssue="$(echo $msgCommit | grep -o -E '[0-9]+')"
numberIssue="$(echo $numberIssue | cut -f1 -d ' ')"

# Prepara o comentário
comment="Data: $(date +%d/%m/%y-%T) \nAutor: $(git config user.name) \nArquivos envolvidos: $(git diff --name-only HEAD HEAD~1) \nComentário do log: $msgCommit"

# Realliza um post na api
curl -X POST -H "Accept: application/vnd.github.v3+json " -H "Authorization: token c49d922894242d0e925a9e423d27a6a911239774" https://api.github.com/repos/$user/$repo/issues/$numberIssue/comments -d "{ \"body\":\"$comment\"}"
